In [1]:
import cv2
import numpy as np
import face_recognition
import os
from datetime import datetime

In [2]:
path = 'Images'
images = []
classNames = []
mylist = os.listdir(path)

print(mylist)

for cls in mylist:
    currentImg = cv2.imread(f'{path}/{cls}')
    images.append(currentImg)
    classNames.append(os.path.splitext(cls)[0])
    
print(classNames)



def findencodings(images):
    encodinglist = []
    for img in images:
        img = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
        encodings = face_recognition.face_encodings(img)[0]
        encodinglist.append(encodings)
        
    return encodinglist

def markattendance(name):
    with open('Attendance.csv', 'r+') as f:
        mydata = f.readlines()
        namelist = []
        print(mydata)
        
        for line in mydata:
            entry = line.split(',')
            namelist.append(entry[0])
        if name not in namelist:
            now = datetime.now()
            time = now.strftime('%H:%M:%S')
            f.writelines(f'\n{name},{time}')




    

encodelistknown = findencodings(images)

print('Encoding complete')

['chiru.jpeg', 'Gandhi.jpeg', 'Elon.jpeg', 'Modi.jpeg']
['chiru', 'Gandhi', 'Elon', 'Modi']
Encoding complete


In [3]:
cap = cv2.VideoCapture(0)

while True:
    success , img = cap.read()
    imgs = cv2.resize(img,(0,0) , None, 0.25,0.25)
    imgs = cv2.cvtColor(imgs,cv2.COLOR_BGR2RGB)
    
    faceslocation = face_recognition.face_locations(imgs)
    encodingcurrent = face_recognition.face_encodings(imgs,faceslocation)
    
    for encode,face in zip(encodingcurrent,faceslocation):
        matches = face_recognition.compare_faces(encodelistknown,encode)
        facedistance = face_recognition.face_distance(encodelistknown,encode)
        print(facedistance)
        
        matchindex = np.argmin(facedistance)
        
        
        if matches[matchindex]:
            name = classNames[matchindex].upper()
            print(name)
            
            y1,x2,y2,x1 = face
            y1,x2,y2,x1 = y1*4, x2*4, y2*4, x1*4
            cv2.rectangle(img, (x1,y1) , (x2,y2), (0,255,0), 2)
            cv2.rectangle(img,(x1,y2-35), (x2,y2), (0,255,0), cv2.FILLED)
            
            cv2.putText(img,name,(x1+6,y2-6), cv2.FONT_HERSHEY_COMPLEX,1,(2555,255,255),2)
            markattendance(name)
            
            
    cv2.imshow('Webcam',img)
    k = cv2.waitKey(1)
    if k == ord('q'):
        break
        
        
        
cap.release()
cv2.destroyAllWindows()
    

QObject::moveToThread: Current thread (0x5583c8f83b20) is not the object's thread (0x5583c901c350).
Cannot move to target thread (0x5583c8f83b20)

QObject::moveToThread: Current thread (0x5583c8f83b20) is not the object's thread (0x5583c901c350).
Cannot move to target thread (0x5583c8f83b20)

QObject::moveToThread: Current thread (0x5583c8f83b20) is not the object's thread (0x5583c901c350).
Cannot move to target thread (0x5583c8f83b20)

QObject::moveToThread: Current thread (0x5583c8f83b20) is not the object's thread (0x5583c901c350).
Cannot move to target thread (0x5583c8f83b20)

QObject::moveToThread: Current thread (0x5583c8f83b20) is not the object's thread (0x5583c901c350).
Cannot move to target thread (0x5583c8f83b20)

QObject::moveToThread: Current thread (0x5583c8f83b20) is not the object's thread (0x5583c901c350).
Cannot move to target thread (0x5583c8f83b20)

QObject::moveToThread: Current thread (0x5583c8f83b20) is not the object's thread (0x5583c901c350).
Cannot move to tar

[0.26418997 0.72181239 0.8154822  0.62278701]
CHIRU
['Name,Time\n', '\n', 'CHIRU,14:11:15\n', 'GANDHI,14:11:30\n', 'MODI,14:11:52\n', 'ELON,14:11:57']
[0.33771137 0.70742093 0.84592959 0.62994133]
CHIRU
['Name,Time\n', '\n', 'CHIRU,14:11:15\n', 'GANDHI,14:11:30\n', 'MODI,14:11:52\n', 'ELON,14:11:57']
[0.23864284 0.73169868 0.83026173 0.63143393]
CHIRU
['Name,Time\n', '\n', 'CHIRU,14:11:15\n', 'GANDHI,14:11:30\n', 'MODI,14:11:52\n', 'ELON,14:11:57']
[0.26394567 0.75474609 0.82063093 0.63426557]
CHIRU
['Name,Time\n', '\n', 'CHIRU,14:11:15\n', 'GANDHI,14:11:30\n', 'MODI,14:11:52\n', 'ELON,14:11:57']
[0.31650486 0.70847269 0.80068559 0.62121762]
CHIRU
['Name,Time\n', '\n', 'CHIRU,14:11:15\n', 'GANDHI,14:11:30\n', 'MODI,14:11:52\n', 'ELON,14:11:57']
[0.26428356 0.70410592 0.81688778 0.64132087]
CHIRU
['Name,Time\n', '\n', 'CHIRU,14:11:15\n', 'GANDHI,14:11:30\n', 'MODI,14:11:52\n', 'ELON,14:11:57']
[0.29736961 0.70885262 0.82140613 0.6244483 ]
CHIRU
['Name,Time\n', '\n', 'CHIRU,14:11:15\n', 

[0.69333434 0.33920589 0.8186335  0.66710164]
GANDHI
['Name,Time\n', '\n', 'CHIRU,14:11:15\n', 'GANDHI,14:11:30\n', 'MODI,14:11:52\n', 'ELON,14:11:57']
[0.68332702 0.38656644 0.81687977 0.67990705]
GANDHI
['Name,Time\n', '\n', 'CHIRU,14:11:15\n', 'GANDHI,14:11:30\n', 'MODI,14:11:52\n', 'ELON,14:11:57']
[0.70713125 0.36302936 0.83824484 0.68901021]
GANDHI
['Name,Time\n', '\n', 'CHIRU,14:11:15\n', 'GANDHI,14:11:30\n', 'MODI,14:11:52\n', 'ELON,14:11:57']
[0.7251118  0.37992841 0.81874471 0.70640567]
GANDHI
['Name,Time\n', '\n', 'CHIRU,14:11:15\n', 'GANDHI,14:11:30\n', 'MODI,14:11:52\n', 'ELON,14:11:57']
[0.76995712 0.39563884 0.79792799 0.72948908]
GANDHI
['Name,Time\n', '\n', 'CHIRU,14:11:15\n', 'GANDHI,14:11:30\n', 'MODI,14:11:52\n', 'ELON,14:11:57']
[0.68849212 0.3357542  0.80409574 0.68359695]
GANDHI
['Name,Time\n', '\n', 'CHIRU,14:11:15\n', 'GANDHI,14:11:30\n', 'MODI,14:11:52\n', 'ELON,14:11:57']
[0.74909528 0.38849078 0.83634795 0.73732268]
GANDHI
['Name,Time\n', '\n', 'CHIRU,14:11:

[0.84822011 0.81695511 0.45494225 0.79729912]
ELON
['Name,Time\n', '\n', 'CHIRU,14:11:15\n', 'GANDHI,14:11:30\n', 'MODI,14:11:52\n', 'ELON,14:11:57']
[0.84637342 0.83011817 0.45630077 0.81635404]
ELON
['Name,Time\n', '\n', 'CHIRU,14:11:15\n', 'GANDHI,14:11:30\n', 'MODI,14:11:52\n', 'ELON,14:11:57']
[0.81949378 0.78525022 0.41188956 0.78852819]
ELON
['Name,Time\n', '\n', 'CHIRU,14:11:15\n', 'GANDHI,14:11:30\n', 'MODI,14:11:52\n', 'ELON,14:11:57']
[0.84973567 0.80243245 0.39825087 0.81729521]
ELON
['Name,Time\n', '\n', 'CHIRU,14:11:15\n', 'GANDHI,14:11:30\n', 'MODI,14:11:52\n', 'ELON,14:11:57']
[0.86682719 0.81260273 0.39406586 0.84316224]
ELON
['Name,Time\n', '\n', 'CHIRU,14:11:15\n', 'GANDHI,14:11:30\n', 'MODI,14:11:52\n', 'ELON,14:11:57']
[0.81945342 0.78704371 0.39507964 0.81504579]
ELON
['Name,Time\n', '\n', 'CHIRU,14:11:15\n', 'GANDHI,14:11:30\n', 'MODI,14:11:52\n', 'ELON,14:11:57']
[0.83940282 0.79569942 0.42355164 0.82806646]
ELON
['Name,Time\n', '\n', 'CHIRU,14:11:15\n', 'GANDHI

[0.62994929 0.75750562 0.84767684 0.61827508]
[0.6417108  0.73418296 0.82452001 0.60134378]
[0.63151139 0.74256859 0.84412334 0.61684998]
[0.62453595 0.73277401 0.84658117 0.59738419]
MODI
['Name,Time\n', '\n', 'CHIRU,14:11:15\n', 'GANDHI,14:11:30\n', 'MODI,14:11:52\n', 'ELON,14:11:57']
[0.66114143 0.76021894 0.83773506 0.58717274]
MODI
['Name,Time\n', '\n', 'CHIRU,14:11:15\n', 'GANDHI,14:11:30\n', 'MODI,14:11:52\n', 'ELON,14:11:57']
[0.6368034  0.73779429 0.84589138 0.6219417 ]
[0.62678087 0.74771711 0.85155552 0.60252222]
[0.61567732 0.72223547 0.86231382 0.59321967]
MODI
['Name,Time\n', '\n', 'CHIRU,14:11:15\n', 'GANDHI,14:11:30\n', 'MODI,14:11:52\n', 'ELON,14:11:57']
[0.62404279 0.74460883 0.861551   0.61917606]
[0.6641076  0.74281301 0.84439204 0.61101208]
[0.63626157 0.73114743 0.86255082 0.60517729]
[0.64567966 0.7463521  0.84511512 0.5829049 ]
MODI
['Name,Time\n', '\n', 'CHIRU,14:11:15\n', 'GANDHI,14:11:30\n', 'MODI,14:11:52\n', 'ELON,14:11:57']
[0.64430706 0.73544183 0.8568907